### ISSUE TITLE
具体的使用有说明么？

### ISSUE THREAD

**Issue by buzai** [die-welle/koa-qiniu#1]

**Comment by Cap32** [comment]
此项目已经不在维护了。

如果你需要在服务器端使用七牛，推荐使用 [官方的七牛 SDK](https://github.com/qiniu/nodejs-sdk), 如果你需要在前端使用七牛上传，可以考虑我们的轻量级前端七牛上传工具 [tiny-qiniu](https://github.com/die-welle/tiny-qiniu)

**Comment by buzai** [comment]
@Cap32 前端上传文件，需要我在后台传回一个ｔｏｋｅｎ然后他上传后把返回的文件名发给我后台，然后我把文件名和这个用户绑定是吧．
但是这样安全么？

**Comment by Cap32** [comment]
token 时效性不长的话还是 OK 的
